# 25-09 - Added passing default hosts to container
apiVersion: v1
kind: Pod
metadata:
  name: testhost 
  namespace: testhost
spec:
  containers:
  - name: waf-k8s-testhost 
    image: vmummer/cpwaftesthost:latest
    imagePullPolicy: Always
#
    env:
    - name: DEFAULT_URL_CPTRAFFIC
      value: http://juiceshop.lab
    - name: DEFAULT_URL_CPAPI
      value: http://vampi.lab
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]

